set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Selection style
set -g mode-style "bg=#ffffff,fg=#000000"
set -g message-style "bg=#ffffff,fg=#000000"
set -g message-command-style "bg=#ffffff,fg=#000000"

set -g history-limit 100000
set -g mouse on
unbind -T copy-mode-vi MouseDragEnd1Pane
setw -g mode-keys vi

# To make double click select whole paths
setw -g word-separators ' @"=()[]'
setw -ag word-separators "'"

# Status bar
set -g status-position top
set -g status-interval 1
# Make it "transparent"
set -g status-style bg=default,fg=default

# Active window
set -g window-status-current-style fg=#000000,bg=#ffffff
set -g window-status-format " #W "
set -g window-status-current-format " #[bold]#W#[default] "

# Right side info
set -g status-right " #h | %d-%m-%Y %H:%M:%S %Z "
set -g status-right-length 100

## prefix + I
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @scroll-speed-num-lines-per-scroll 1
set -g @scroll-down-exit-copy-mode 0

## git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'

